"""Add public  to chat_rooms

Revision ID: e1c821240c1d
Revises: ab09f002f8e4
Create Date: 2025-11-04 15:31:06.646416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c821240c1d'
down_revision = 'ab09f002f8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_chat_room_public', ['is_public'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_room_public')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
